### ISSUE TITLE
Error Running CircMarker:  terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by ivlachos** [lxwgcool/CircMarker#2]
We’ve just started exploring CircMarker.
 
It’s mentioned in the README that it can support now genome-wide predictions.
 
We’re using a fasta file with all chromosomes included (primary assembly from Ensembl)
 
And the accompanying gtf.
 
We get this error:
 
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted (core dumped)
 
It’s working for a little while and then it breaks.
 
No results are output.
 
This is the config.ini we’re using:
 
[General]
Reference=/GRCm38/ENS.93/Sequence/Mus_musculus.GRCm38.dna.primary_assembly.fa
GTF=/GRCm38/ENS.93/Annotation/Mus_musculus.GRCm38.93.gtf
Reads1=/Samples/1_S1_R1_001.fastq.gz
Reads2=/Samples/1_S1_R2_001.fastq.gz
[Parameters]
MinSupportReads=1
MaxSupportReads=999
ReadsLen=101
KmerRatio=30
[Results]
CurResult=
SimulationResult=
CIRIResult=
CIRCexplorerResult=
FindCircResult=
CircBaseResult=
[HitCompare]
CIRIHit=
CurHit=
FindCircHit=
CircExplorerHit=
CurChromIndex=
[Mapping]
BWA=

Any ideas?

**Comment by chaochaowong** [comment]
I got exactly the same error message as @ivlachos. Too bad that the author is not responding anymore.

**Comment by lxwgcool** [comment]
Hey guys, 

Thank you so much for using circmarker. I am so sorry for not responding your tickets on time. 2019 is very tough for me. Everything get back on track right now. Back to this ticket, this should be a bug in code. If it is possible, could you share the input file with me, including reads , reference and gtf? I will try to review the code to avoid such potential error as well. Please feel free to let me know if you have any questions.

**Comment by lxwgcool** [comment]
> I got exactly the same error message as @ivlachos. Too bad that the author is not responding anymore.
I am so sorry about that. Please check my comments in this tickets.

**Comment by chaochaowong** [comment]
Hi, @lxwgcool, thank you for your response. Really appreciated it and glad to hear that you are back on track. 

 I think the problem was induced by the incompatible sequence region names between the reference genome (*.fa) and gene annotation (*.gtf), e.g., chr1 vs. 1.    After using circMarker for a week, I do have some suggestions to improve the user's experience.
1. Check fastq file existence: `circMarker` does not check whether the fastq file exists. With invalid fastq file, It will  the run and render empty summary file.
2. Check sequence region names between *.fa and *.gtf files: some users might mistakenly use NCBI/EMSEMBL sequence level style (1,2, ..) for genome reference and UCSC style (chr1, chr2, ..) for gene annotation. Be nice to check and give a warning to the user.
3. Allow user to define the number of core: circMarker detects the number of available cores and use at least 25 cores. The parallelization is great. But when using shared cluster resources, core usage might be limited to some users.
4. Documentation. What's the format of the output and what they represent? circular RNAs with exons or back-spliced junction? What does the fourth column mean? the number of hit from the read??? 

Sorry for the bombardment. Can you at least now tell me what the fourth column means in the result files (Brief_sum.txt)? thanks a lot.

**Comment by lxwgcool** [comment]
@TapscottLab 
Thanks  for your comments. It's all set. 
Here is the details of my latest submission: 
1: Add new features for checking errors 
  (1) Check fastq file existence
  (2) Check fastq file existence
  (3) Check Annotation file (gtf) existence
2: Check the chromosome naming rule between annotation and reference. 
3: Fix bug: out of index substr
  (1) CircMarker first sampling 8 kmers from reads to check if current reads may contribute a potential circular RNA. You may get this error if the reads is too short (e.g. after trimmomatic). This bug has been fixed in this version.

Here are my comments for your questions: 
Q1: Allow user to define the number of core: circMarker detects the number of available cores and use at least 25 cores. The parallelization is great. But when using shared cluster resources, core usage might be limited to some users
Comments: 
If you have enough computing resources in one computing node, you can get the best performance if the number of cores you applied equals to the number of chromosomes in your annotation (e.g. 24 cores for WES (23 + M)). Since circmarker uses multiple threads for parallel computing, all of the cores you requested should be in the same computing node. In another word, the cores across different HPC computing nodes cannot be used by circmarker at the same time. Actually, any multiple threads based software (such as BWA, bcl2fastq) can not use multiple cores across different nodes.

Q2: What's the format of the output and what they represent?
Comments: 
For "./Brief_sum.txt"
Col 1: Chromosme name
Col 2: CircRNA starting position
Col 3: CircRNA ending position
Col 4: Number of reads that support current circular RNA
Col 5: Strand
Col 6: Type of Circular RNA
       a) S: self-circle Case
       b) R: Regular-circle Case

Please pull my latest version and run your project again.
Best
Xin

**Comment by chaochaowong** [comment]
Thank you very much for your prompt reply.

**Comment by lxwgcool** [comment]
It should be all set. Waiting for additional feedback
