### ISSUE TITLE
pipeline question: does circMarker work on total RNA, ribo- RNA-seq

### ISSUE THREAD

**Issue by chaochaowong** [lxwgcool/CircMarker#5]
Has `circMarker` been tested on total RNA (includes both poly(A) and non-poly(A) transcripts), ribo- RNA-Seq? Does it work?  will you suggest I start with unmapped reads, instead of all reads? Have you compared the results with _CIRCexplorere_ in this case?  

Thank you very much,
CJ

**Comment by lxwgcool** [comment]
@TapscottLab 
Please check my comments below:
1: Has circMarker been tested on total RNA (includes both poly(A) and non-poly(A) transcripts), ribo- RNA-Seq? Does it work? 
I think so. Please check my paper: 
https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-018-4926-0
https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-019-6154-7

2: will you suggest I start with unmapped reads, instead of all reads?
No idea why you plan to start with unmapped reads. CircMarker is a kmer-based rather than mapping-based tool. In another word, CircMarker still try to find the mapped sequence, however, it does not rely on third-party mapping tools. 

3: Have you compared the results with CIRCexplorere in this case?
I think so. Please check my paper.

**Comment by lxwgcool** [comment]
It should be all set. Waiting for response from user.

**Comment by chaochaowong** [comment]
Sorry for the late reply and thank you for the response. I read the papers again more carefully and yes, I am convinced that circMarker works for the ribosomal depleted total RNA-seq. Thank you for the information.
